resolver: lts-17.13

extra-deps:
  # At the time of writing, no snapshot includes Clash 1.4 yet so we add it - and
  # its dependencies - manually.
  - lazysmallcheck-0.6
  - Stream-0.4.7.2
  - arrows-0.4.4.2
  - clash-prelude-1.4.2
  - clash-lib-1.4.2
  - clash-ghc-1.4.2
  - github: tilk/yieldfsm
    commit: d81c5811098e74d55abf48ec7392fb5241d364b8

